# serverless.yml
# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: yle-tiksuttelija-slack-app
frameworkVersion: '2'
provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET_TIKSUTTELIJA}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN_TIKSUTTELIJA}
    TIKSU_INSTANCE: ${env:TIKSU_INSTANCE}
    TIKSU_USERID: ${env:TIKSU_USERID}
    TIKSU_PASSWORD: ${env:TIKSU_PASSWORD}
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline

